name: dagenergi
description: "Dagenergi app for metric"

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  image_picker:
  get: any
  flutter_screenutil:
  image:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: any
  geolocator: ^11.0.0
  firebase_core: any
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.16.0
  dio: any
  intl: ^0.18.1
  path: any
  path_provider: any
  camera: any
  s3_storage: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: any

flutter:

  uses-material-design: true


  assets:
    - assets/images/
